/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TlspoolSocket */

#ifndef _Included_TlspoolSocket
#define _Included_TlspoolSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TlspoolSocket
 * Method:    startTls0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TlspoolSocket_startTls0
  (JNIEnv *, jobject);

/*
 * Class:     TlspoolSocket
 * Method:    readEncrypted
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_TlspoolSocket_readEncrypted
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     TlspoolSocket
 * Method:    writeEncrypted
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_TlspoolSocket_writeEncrypted
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
