/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TlspoolSocket_PlainOutputStream */

#ifndef _Included_TlspoolSocket_PlainOutputStream
#define _Included_TlspoolSocket_PlainOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TlspoolSocket_PlainOutputStream
 * Method:    writePlain
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_TlspoolSocket_00024PlainOutputStream_writePlain
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
