/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TlspoolSocket_PlainInputStream */

#ifndef _Included_TlspoolSocket_PlainInputStream
#define _Included_TlspoolSocket_PlainInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef TlspoolSocket_PlainInputStream_MAX_SKIP_BUFFER_SIZE
#define TlspoolSocket_PlainInputStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     TlspoolSocket_PlainInputStream
 * Method:    readPlain
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_TlspoolSocket_00024PlainInputStream_readPlain
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
